#!/usr/bin/env bash
# journal-precompact.sh — Auto-write checkpoint to journal before compaction
#
# Fires on PreCompact hook (before Claude Code runs /compact).
# Reads trigger and custom_instructions from stdin JSON.
# Writes a checkpoint entry to .project-log/journal.jsonl.
# Exits silently on any error — never blocks compaction.

set -euo pipefail

# --- Parse stdin ---
INPUT="$(cat)"

TRIGGER="$(echo "$INPUT" | jq -r '.trigger // "auto"' 2>/dev/null || echo "auto")"
CUSTOM_INSTRUCTIONS="$(echo "$INPUT" | jq -r '.custom_instructions // ""' 2>/dev/null || echo "")"

# --- Find repo root ---
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0

# --- Check journal initialized ---
JOURNAL="$REPO_ROOT/.project-log/journal.jsonl"
[ -f "$JOURNAL" ] || exit 0

# --- Check scripts present ---
LOG_SCRIPT="$REPO_ROOT/.project-log/journal_log.py"
[ -f "$LOG_SCRIPT" ] || exit 0

# --- Get git state ---
BRANCH="$(git branch --show-current 2>/dev/null || echo "unknown")"
GIT_STATUS="$(git status --short 2>/dev/null || echo "")"

if [ -n "$GIT_STATUS" ] || [ "$BRANCH" != "main" ]; then
    MODIFIED="$(echo "$GIT_STATUS" | awk '{print $2}' | tr '\n' ',' | sed 's/,$//')"
    GIT_STATE="branch: $BRANCH"
    [ -n "$MODIFIED" ] && GIT_STATE="$GIT_STATE | modified: $MODIFIED"
else
    GIT_STATE=""
fi

# --- Build in_progress note ---
IN_PROGRESS="Auto-captured at PreCompact (trigger: $TRIGGER)."
if [ -n "$CUSTOM_INSTRUCTIONS" ]; then
    IN_PROGRESS="$IN_PROGRESS User compact note: $CUSTOM_INSTRUCTIONS"
fi

# --- Write checkpoint ---
ARGS=(
    --type checkpoint
    --in-progress "$IN_PROGRESS"
    --key-context "This checkpoint was auto-generated by the PreCompact hook. Use /resume to load it. Run /checkpoint manually for a richer synthesis."
)

[ -n "$GIT_STATE" ] && ARGS+=(--git-state "$GIT_STATE")

python3 "$LOG_SCRIPT" "${ARGS[@]}" >/dev/null 2>&1 || exit 0

exit 0
